import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — PortfolioIQ",
};

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 sm:px-6 py-12">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-500 mb-8">Last updated: February 15, 2026</p>

      <div className="prose prose-slate prose-sm max-w-none space-y-6">
        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">1. Acceptance of Terms</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            By accessing or using PortfolioIQ (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">2. Description of Service</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            PortfolioIQ is a trading performance intelligence platform that uses artificial intelligence to analyze user-submitted trade history and generate behavioral analysis reports (&quot;Leak Reports&quot;). The Service is provided for educational and informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">3. Account Registration</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            To use the Service, you must create an account with a valid email address and password. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years old to create an account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">4. Free and Paid Plans</h2>
          <div className="space-y-2">
            <p className="text-sm text-slate-700 leading-relaxed">
              <strong>Free Tier:</strong> Each user receives 3 free Leak Reports for life (for image/CSV uploads). Sample reports using demonstration data do not count toward this limit.
            </p>
            <p className="text-sm text-slate-700 leading-relaxed">
              <strong>Pro Plan:</strong> The Pro subscription provides unlimited Leak Report generation for $29/month. Subscriptions are processed through Stripe and renew automatically until cancelled.
            </p>
            <p className="text-sm text-slate-700 leading-relaxed">
              <strong>Sample Reports:</strong> Sample reports are limited to 5 per day and are provided for demonstration purposes only.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">5. User Content</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            You retain ownership of all trade data and content you upload to the Service. By uploading content, you grant us a limited license to process, analyze, and store your data solely for the purpose of providing the Service. We will not share your trade data with other users or use it for purposes beyond providing your reports.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">6. Prohibited Use</h2>
          <p className="text-sm text-slate-700 leading-relaxed">You agree not to:</p>
          <ul className="text-sm text-slate-700 leading-relaxed list-disc pl-5 space-y-1 mt-2">
            <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
            <li>Attempt to circumvent usage limits, rate limits, or paywall restrictions</li>
            <li>Use automated systems, bots, or scripts to access the Service without authorization</li>
            <li>Redistribute, resell, or commercially exploit reports generated by the Service</li>
            <li>Upload malicious files, attempt to compromise system security, or interfere with Service operation</li>
            <li>Create multiple accounts to circumvent free tier limitations</li>
            <li>Misrepresent AI-generated content as professional financial advice to others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">7. Not Financial Advice</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            The Service does not provide financial advice, investment recommendations, or trading signals. All reports, scores, and suggestions are AI-generated educational content. You acknowledge that trading involves substantial risk and that you are solely responsible for your trading and investment decisions. See our full <Link href="/disclaimer" className="text-brand-accent hover:underline">Disclaimer</Link> for more details.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">8. Subscription and Billing</h2>
          <div className="space-y-2">
            <p className="text-sm text-slate-700 leading-relaxed">
              Pro subscriptions are billed monthly through Stripe. You may cancel your subscription at any time through the Stripe customer portal. Cancellation takes effect at the end of your current billing period. We do not offer partial refunds for unused time within a billing cycle.
            </p>
            <p className="text-sm text-slate-700 leading-relaxed">
              We reserve the right to change subscription pricing with 30 days&apos; notice. Existing subscribers will be notified before any price changes take effect.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">9. Termination</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            We reserve the right to suspend or terminate your account at any time for violation of these terms, abuse of the Service, or at our sole discretion. Upon termination, your right to use the Service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">10. Limitation of Liability</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            To the maximum extent permitted by law, PortfolioIQ and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, or other intangible losses resulting from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">11. Indemnification</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            You agree to indemnify and hold harmless PortfolioIQ and its operators from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these terms, or your violation of any rights of a third party.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">12. Changes to Terms</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            We reserve the right to modify these terms at any time. Material changes will be communicated via email or prominent notice on the Service. Your continued use after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">13. Governing Law</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
          </p>
        </section>

        <div className="pt-4 border-t border-slate-200 text-sm text-slate-500">
          <p>If you have questions about these terms, contact us at <span className="text-brand-accent">team@portfolioiq.pro</span>.</p>
          <p className="mt-2">See also: <Link href="/disclaimer" className="text-brand-accent hover:underline">Disclaimer</Link> · <Link href="/privacy" className="text-brand-accent hover:underline">Privacy Policy</Link></p>
        </div>
      </div>
    </div>
  );
}
