import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — PortfolioIQ",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 sm:px-6 py-12">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Disclaimer</h1>
      <p className="text-sm text-slate-500 mb-8">Last updated: February 15, 2026</p>

      <div className="prose prose-slate prose-sm max-w-none space-y-6">
        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">General Information</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            PortfolioIQ (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) provides this website and all related tools, reports, and services (collectively, the &quot;Service&quot;) for informational and educational purposes only. Nothing on this website constitutes financial advice, investment advice, trading advice, or any other sort of professional advice.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">No Financial Advice</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            The content provided through our Service, including but not limited to Leak Reports, trade analysis, behavioral insights, risk checklists, and fix plans, is generated using artificial intelligence and algorithmic analysis. This content is not intended to be and should not be construed as financial advice, investment recommendations, or trading signals. You should not make any financial decisions based solely on the information provided by PortfolioIQ.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">No Guarantees</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, analysis, or related content provided through the Service. Past performance is not indicative of future results. Any reliance you place on such information is strictly at your own risk. Trading and investing involve substantial risk of loss and are not suitable for every person.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">AI-Generated Content</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            Our reports and analyses are generated by artificial intelligence models. While we strive for accuracy, AI-generated content may contain errors, omissions, or misinterpretations of your trading data. You are responsible for verifying all information and should not rely on AI-generated reports as the sole basis for any trading or investment decisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">Sample Data</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            Sample trade datasets and reports generated from sample data are provided for demonstration and testing purposes only. These examples may not reflect real market conditions, execution quality, slippage, commissions, taxes, or brokerage constraints. No recommendation is being made to buy, sell, or hold any security or strategy based on sample data.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">Limitation of Liability</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            In no event shall PortfolioIQ, its operators, affiliates, or partners be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or other intangible losses resulting from your use of or inability to use the Service, any content obtained from the Service, or any trading or investment decisions made based on our content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">Professional Advice</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            Always consult with a qualified financial advisor, investment professional, or other appropriate professional before making any financial decisions. PortfolioIQ is not a registered broker-dealer, investment adviser, or financial planner.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-2">Changes to This Disclaimer</h2>
          <p className="text-sm text-slate-700 leading-relaxed">
            We reserve the right to update or modify this disclaimer at any time without prior notice. Your continued use of the Service after any changes constitutes acceptance of the updated disclaimer.
          </p>
        </section>

        <div className="pt-4 border-t border-slate-200 text-sm text-slate-500">
          <p>If you have questions about this disclaimer, contact us at <span className="text-brand-accent">team@portfolioiq.pro</span>.</p>
          <p className="mt-2">See also: <Link href="/privacy" className="text-brand-accent hover:underline">Privacy Policy</Link> · <Link href="/terms" className="text-brand-accent hover:underline">Terms of Service</Link></p>
        </div>
      </div>
    </div>
  );
}
